sh euclidtidy.sh bookI/bookI.html
sh euclidtidy.sh bookI/cn.html
sh euclidtidy.sh bookI/defI1.html
sh euclidtidy.sh bookI/defI10.html
sh euclidtidy.sh bookI/defI11.html
sh euclidtidy.sh bookI/defI13.html
sh euclidtidy.sh bookI/defI15.html
sh euclidtidy.sh bookI/defI19.html
sh euclidtidy.sh bookI/defI2.html
sh euclidtidy.sh bookI/defI20.html
sh euclidtidy.sh bookI/defI22.html
sh euclidtidy.sh bookI/defI23.html
sh euclidtidy.sh bookI/defI3.html
sh euclidtidy.sh bookI/defI4.html
sh euclidtidy.sh bookI/defI5.html
sh euclidtidy.sh bookI/defI6.html
sh euclidtidy.sh bookI/defI7.html
sh euclidtidy.sh bookI/defI8.html
sh euclidtidy.sh bookI/defI9.html
sh euclidtidy.sh bookI/post1.html
sh euclidtidy.sh bookI/post2.html
sh euclidtidy.sh bookI/post3.html
sh euclidtidy.sh bookI/post4.html
sh euclidtidy.sh bookI/post5.html
sh euclidtidy.sh bookI/propI1.html
sh euclidtidy.sh bookI/propI10.html
sh euclidtidy.sh bookI/propI11.html
sh euclidtidy.sh bookI/propI12.html
sh euclidtidy.sh bookI/propI13.html
sh euclidtidy.sh bookI/propI14.html
sh euclidtidy.sh bookI/propI15.html
sh euclidtidy.sh bookI/propI16.html
sh euclidtidy.sh bookI/propI17.html
sh euclidtidy.sh bookI/propI18.html
sh euclidtidy.sh bookI/propI19.html
sh euclidtidy.sh bookI/propI2.html
sh euclidtidy.sh bookI/propI20.html
sh euclidtidy.sh bookI/propI21.html
sh euclidtidy.sh bookI/propI22.html
sh euclidtidy.sh bookI/propI23.html
sh euclidtidy.sh bookI/propI24.html
sh euclidtidy.sh bookI/propI25.html
sh euclidtidy.sh bookI/propI26.html
sh euclidtidy.sh bookI/propI27.html
sh euclidtidy.sh bookI/propI28.html
sh euclidtidy.sh bookI/propI29.html
sh euclidtidy.sh bookI/propI3.html
sh euclidtidy.sh bookI/propI30.html
sh euclidtidy.sh bookI/propI31.html
sh euclidtidy.sh bookI/propI32.html
sh euclidtidy.sh bookI/propI33.html
sh euclidtidy.sh bookI/propI34.html
sh euclidtidy.sh bookI/propI35.html
sh euclidtidy.sh bookI/propI36.html
sh euclidtidy.sh bookI/propI37.html
sh euclidtidy.sh bookI/propI38.html
sh euclidtidy.sh bookI/propI39.html
sh euclidtidy.sh bookI/propI4.html
sh euclidtidy.sh bookI/propI40.html
sh euclidtidy.sh bookI/propI41.html
sh euclidtidy.sh bookI/propI42.html
sh euclidtidy.sh bookI/propI43.html
sh euclidtidy.sh bookI/propI44.html
sh euclidtidy.sh bookI/propI45.html
sh euclidtidy.sh bookI/propI46.html
sh euclidtidy.sh bookI/propI47.html
sh euclidtidy.sh bookI/propI48.html
sh euclidtidy.sh bookI/propI5.html
sh euclidtidy.sh bookI/propI6.html
sh euclidtidy.sh bookI/propI7.html
sh euclidtidy.sh bookI/propI8.html
sh euclidtidy.sh bookI/propI9.html
